

  0%|▎                                                                                | 1/250 [00:51<3:33:02, 51.33s/it]

  1%|▋                                                                                | 2/250 [01:46<3:40:50, 53.43s/it]

  1%|▉                                                                                | 3/250 [02:37<3:36:10, 52.51s/it]
{'loss': 0.3285, 'grad_norm': 0.07158318907022476, 'learning_rate': 0.00012, 'epoch': 0.01}


  2%|█▌                                                                               | 5/250 [03:56<3:02:51, 44.78s/it]
{'loss': 0.3227, 'grad_norm': 0.07070557028055191, 'learning_rate': 0.0002, 'epoch': 0.02}






















































































































































































































































































































































































































































  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 155, in send_to_device
    return tensor.to(device, non_blocking=non_blocking)
TypeError: BatchEncoding.to() got an unexpected keyword argument 'non_blocking'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/geo_llm/llama3-finetune/HuMob_wandb.py", line 163, in <module>
  File "<string>", line 126, in train
  File "<string>", line 435, in _fast_inner_training_loop
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/trainer.py", line 2793, in _maybe_log_save_evaluate
    metrics = self._evaluate(trial, ignore_keys_for_eval)
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/trainer.py", line 2750, in _evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/trainer.py", line 3641, in evaluate
    output = eval_loop(
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/trainer.py", line 3816, in evaluation_loop
    for step, inputs in enumerate(dataloader):
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/accelerate/data_loader.py", line 463, in __iter__
    current_batch = send_to_device(current_batch, self.device, non_blocking=self._non_blocking)
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/accelerate/utils/operations.py", line 157, in send_to_device
    return tensor.to(device)
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 803, in to
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
  File "/home/geo_llm/anaconda3/envs/unsloth_env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 803, in <dictcomp>
    self.data = {k: v.to(device=device) for k, v in self.data.items()}
KeyboardInterrupt